language: node_js
node_js:
  - "6.9"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

branches:
  only:
    - develop

before_script:
  - npm install -g @angular/cli

script:
  - ng test -sr
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change