language: node_js
node_js:
  - "10"

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g npm
  - npm -v
  - yarn global add @angular/cli

branches:
  only:
    - develop
    - /^greenkeeper/.*$/
    - /^feature/.*$/
    - /^release/.*$/
    - /^hotfix/.*$/
    - codecovTest

before_script:

script:
  - ng lint --type-check
  - ng test --no-progress -sr -cc

after_success:
  - ./node_modules/.bin/codecov

notifications:
  email:
    on_failure: change
    on_success: change
