version: 2
jobs:
  build:
    branches:
      only:
        - develop
        - /^greenkeeper/.*$/
    working_directory: ~/SBAdBs4Ng2
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: SBAdBs4Ng2-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          yarn install
      - save_cache:
          key: SBAdBs4Ng2-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          yarn run test --watch=false --progress=false --browsers=ChromeHeadlessCI

      - run:
          command: ./node_modules/.bin/codecov
          when: on_success
