version: 2
jobs:
  build:
    working_directory: ~/SBAdBs4Ng2
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: SBAdBs4Ng2-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: SBAdBs4Ng2-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: yarn run test -- --single-run --no-progress --browser=ChromeHeadlessCI
      - run: yarn run e2e -- --no-progress --config=protractor-ci.conf.js